package br.com.unip.cadastro.exception

enum class ECodigoErro {

    ERRO_INESPERADO("000"),
    PARAMETRO_INVALIDO("001"),
    CAMPO_OBRIGATORIO("002"),
    ACESSO_NEGADO("003"),
    TOKEN_EXPIRADO("004"),
    TOKEN_INVALIDO("005"),
    FORMATO_DATA_INVALIDA("006"),
    CAMPO_DEVE_SER_NUMERICO("007"),
    CNPJ_INVALIDO("0008"),
    CNPJ_OBRIGATORIO("0009"),
    CPF_INVALIDO("0010"),
    CPF_OBRIGATORIO("011"),
    UUID_CADASTRO_OBRIGATORIO("012"),
    CADASTRO_JA_ATIVO("013"),
    NOME_OBRIGATORIO("014"),
    RAZAO_SOCIAL_OBRIGATORIO("015"),
    DATA_DEVE_SER_RETROATIVA("016"),
    CAMPO_TELEFONE_DEVE_SER_NUMERICO("017"),
    CADASTRO_NAO_ENCONTRADO("018"),
    CAMPO_TAMANHO_LIMITE_EXCEDENTE("019"),
    CAMPO_TELEFONE_EXCEDE_TAMANHO_LIMITE("020"),
    CAMPO_BAIRRO_OBRIGATORIO("021"),
    CAMPO_CIDADE_OBRIGATORIO("022"),
    CAMPO_CEP_OBRIGATORIO("023"),
    CAMPO_LOGRADOURO_OBRIGATORIO("024"),
    CAMPO_NUMERO_OBRIGATORIO("025"),
    CAMPO_NUMERO_DEVE_SER_NUMERICO("026"),
    CAMPO_CEP_INVALIDO("027"),
    CAMPO_CEP_DEVE_SER_NUMERICO("028"),
    CAMPO_ESTADO_OBRIGATORIO("029");

    val codigo: String

    constructor(codigo: String) {
        this.codigo = codigo
    }
}